Dev_Env_Exam_Project/Controllers/CompaniesRolesMVController.cs
using Dev_Env_Exam_Project.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Dev_Env_Exam_Project.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CompaniesRolesMVController : Controller
    {
        private AppDbContext db = new AppDbContext();
        // GET: CompaniesRoles
        public ActionResult Index()
        {
            CompanyRoleViewModel mymodel = new CompanyRoleViewModel();
            mymodel.Companies = db.Companies.ToList();
            mymodel.Roles = db.Roles.ToList();
            return View(mymodel);
        }
    }
}

Dev_Env_Exam_Project/Controllers/CompanyController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Dev_Env_Exam_Project.Models;
using System.Collections;

namespace Dev_Env_Exam_Project.Controllers
{
    [Authorize(Users = "admin@gmail.com")]
    public class CompanyController : Controller
    {
        private AppDbContext db = new AppDbContext();

        // GET: Companies
        public ActionResult Index()
        {
            return View(db.Companies.ToList());
        }

        // GET: Companies/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Company company = db.Companies.Find(id);
            if (company == null)
            {
                return HttpNotFound();
            }
            return View(company);
        }

        // GET: Companies/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Companies/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Name,Address,PhoneNo,Email")] Company company)
        {
            if (ModelState.IsValid)
            {
                //company.CompanyId = 1;
                //Employee employee = new Employee();
                //List<Employee> list = new List<Employee>();
                //employee.EmployeeId = 1;
                //employee.CompanyId = 1;
                //employee.Name = "some employee";
                //employee.email = "email";
                //employee.Address = "address";
                //employee.Phone = "12345678";
                //list.Add(employee);
                //company.Employees = list;
                //Role role = new Role();
                //List<Role> roles = new List<Role>();
                //role.RoleId = 1;
                //role.CompanyId = 1;
                //role.Name = "some role";
                //role.Description = "some descr";
                //roles.Add(role);
                //company.Roles = roles;
                db.Companies.Add(company);
                db.SaveChanges();
                return RedirectToAction("Index", "CompaniesRolesMV");
            }

            return View(company);
        }

        // GET: Companies/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Company company = db.Companies.Find(id);
            if (company == null)
            {
                return HttpNotFound();
            }
            return View(company);
        }

        // POST: Companies/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Name,Address,PhoneNo,Email")] Company company)
        {
            if (ModelState.IsValid)
            {
                db.Entry(company).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", "CompaniesRolesMV");
            }
            return View(company);
        }

        // GET: Companies/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Company company = db.Companies.Find(id);
            if (company == null)
            {
                return HttpNotFound();
            }
            return View(company);
        }

        // POST: Companies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Company company = db.Companies.Find(id);
            db.Companies.Remove(company);
            db.SaveChanges();
            return RedirectToAction("Index", "CompaniesRolesMV");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Dev_Env_Exam_Project/Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Dev_Env_Exam_Project.Models;

namespace Dev_Env_Exam_Project.Controllers
{
    public class RolesController : Controller
    {
        private AppDbContext db = new AppDbContext();

        // GET: Roles
        public ActionResult Index()
        {
            return View(db.Roles.ToList());
        }

        // GET: Roles/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Role role = db.Roles.Find(id);
            if (role == null)
            {
                return HttpNotFound();
            }
            return View(role);
        }

        // GET: Roles/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Roles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "RoleId,Name,Description")] Role role)
        {
            if (ModelState.IsValid)
            {
                role.CompanyId = db.Companies.FirstOrDefault().CompanyId;
                db.Roles.Add(role);
                db.SaveChanges();
                return RedirectToAction("Index", "CompaniesRolesMV");
            }

            return View(role);
        }

        // GET: Roles/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Role role = db.Roles.Find(id);
            if (role == null)
            {
                return HttpNotFound();
            }
            return View(role);
        }

        // POST: Roles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "RoleId,Name,Description")] Role role)
        {
            if (ModelState.IsValid)
            {
                role.CompanyId = db.Companies.FirstOrDefault().CompanyId;
                db.Entry(role).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", "CompaniesRolesMV");
            }
            return View(role);
        }

        // GET: Roles/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Role role = db.Roles.Find(id);
            if (role == null)
            {
                return HttpNotFound();
            }
            return View(role);
        }

        // POST: Roles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Role role = db.Roles.Find(id);
            db.Roles.Remove(role);
            db.SaveChanges();
            return RedirectToAction("Index", "CompaniesRolesMV");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Dev_Env_Exam_Project/Views/CompaniesRolesMV/Index.cshtml
@using Dev_Env_Exam_Project.Models
@model CompanyRoleViewModel

@{
    ViewBag.Title = "Company Profile";
}

<br/><br/>
<h2>Company Profile Page</h2>
<hr/>
@*<p>
    @Html.ActionLink("Create New", "Create")
</p>*@

<div>
    <h4>Company Logo:</h4>
</div>

@{
    IEnumerable<string> file = Directory.EnumerateFiles(Server.MapPath("~/CompanyLogo/"));

    foreach (var path in file)
    {
        var fileName = Path.GetFileName(path);
        <img src="~/CompanyLogo/@fileName" width="200" height="100" />
    }
} 
<br/>
<h3>Company Details</h3>
<hr/>

<table class="table table-striped table-hover table-responsive">
    <tr style="font-size:20px">
        <th>
            Name
        </th>
        <th>
            Address
        </th>
        <th>
           Phone Number
        </th>
        <th>
            Email
        </th>
        <th>
            Options
        </th>
    </tr>

    @foreach (Company company in Model.Companies)
    {
        <tr >
            <td>
                @company.Name
            </td>
            <td class="col-md-4">
                @company.Address
            </td>
            <td>
                @company.PhoneNo
            </td>
            <td>
                @company.Email
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", "Company", new { id = company.CompanyId }, null)&emsp;|&emsp;
                @Html.ActionLink("Details", "Details", "Company", new { id = company.CompanyId }, null)&emsp;|&emsp;
                @Html.ActionLink("Delete", "Delete", "Company", new { id = company.CompanyId }, null)
            </td>
        </tr>
    }

</table>

<br/><br/><br/>

<h3>Roles</h3>
<hr/>
<p>
    @Html.ActionLink("Create New", "Create", "Roles")
</p>
<table id="company_table" class="table table-striped table-hover table-responsive">
    <tr style="font-size:20px">
        <th class="col-md-2">
          Name
        </th>
        <th class="col-md-6">
           Description
        </th>
        <th>
            Options
        </th>
    </tr>

    @foreach (Role role in Model.Roles)
    {
        <tr>
            <td>
                @role.Name
            </td>
            <td>
                    @role.Description
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", "Roles", new { id = role.RoleId }, null) &emsp;|&emsp;
                @Html.ActionLink("Details", "Details", "Roles", new { id = role.RoleId }, null) &emsp;|&emsp;
                @Html.ActionLink("Delete", "Delete", "Roles", new { id = role.RoleId }, null)
            </td>
        </tr>
    }

</table>